Repository Azure/azure-sdk-for-net, pull requests merged in 2018-12, with the labels that each got.

#5073 Updte minor version of Media Services SDK in Management.Media/Microsoft.Azure.Management.Media.csproj
  src/SDKs/Media/Management.Media/Microsoft.Azure.Management.Media.csproj
Labels: Merge Conflicts

#5074 Add ignore scopes to props file for local builds
  Directory.Build.props
Labels: Changes Requested

#5072 Working YML for DotNet on Windows
  .azure-pipelines/client.yml
Labels: Changes Requested

#5080 Device streaming API version(2018-12-01-preview) update for IotHub
  src/SDKs/IotHub/AzSdk.RP.props
  src/SDKs/IotHub/IotHub.Tests/Helpers/IotHubTestUtilities.cs
  src/SDKs/IotHub/IotHub.Tests/ScenarioTests/IotHubLifeCycleTests.cs
  src/SDKs/IotHub/IotHub.Tests/SessionRecords/IotHub.Tests.ScenarioTests.IotHubLifeCycleTests/TestIotHubCertificateLifeCycle.json
  src/SDKs/IotHub/IotHub.Tests/SessionRecords/IotHub.Tests.ScenarioTests.IotHubLifeCycleTests/TestIotHubCreateLifeCycle.json
  src/SDKs/IotHub/IotHub.Tests/SessionRecords/IotHub.Tests.ScenarioTests.IotHubLifeCycleTests/TestIotHubUpdateLifeCycle.json
  src/SDKs/IotHub/Management.IotHub/Generated/IIotHubClient.cs
  src/SDKs/IotHub/Management.IotHub/Generated/IotHubClient.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/IotHubProperties.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/IotHubPropertiesDeviceStreams.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/OperationDisplay.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/RoutingTwin.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/RoutingTwinProperties.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/TestAllRoutesInput.cs
  src/SDKs/IotHub/Management.IotHub/Generated/Models/TestRouteInput.cs
  src/SDKs/IotHub/Management.IotHub/Generated/SdkInfo_iotHubClient.cs
  src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
  src/SDKs/IotHub/Management.IotHub/Properties/AssemblyInfo.cs
  src/SDKs/_metadata/iothub_resource-manager.txt
Labels: Changes Requested

#5056 Updated SDKs for bot framework and ...
  src/SDKs/BotService/Management.BotService/Customizations/BotProperties.cs
  src/SDKs/BotService/Management.BotService/Customizations/MsaAuthenticator.cs
  src/SDKs/BotService/Management.BotService/Microsoft.Azure.Management.BotService.csproj
Labels: Do Not Merge
