Repository Azure/azure-sdk-for-net, pull requests merged in 2019-02, with the labels that each got.

#5196 Adding dispatch child in LUIS Runtime response
  src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Generated/LUISRuntimeClient.cs
  src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Generated/Models/LuisResult.cs
  src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Generated/SdkInfo_LUISRuntimeClient.cs
  src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Microsoft.Azure.CognitiveServices.LUIS.Runtime.csproj
  src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Properties/AssemblyInfo.cs
  src/SDKs/_metadata/cognitiveservices_data-plane_LUIS_Runtime.txt
Labels: Changes Requested

#5234 Move the AzConfig SDK to the central repo
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/Azure.Configuration.Tests.csproj
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/ConfigurationLiveTests.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/ConfigurationMockTests.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/ConfigurationWatcherTests.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/MockHttpClientTransport.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/Readme.md
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/samples/Sample1_HelloWorld.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/samples/Sample4_Logging.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/samples/Sample5_Watcher.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/samples/Sample6_ConfiguringRetries.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/samples/Sample7_ConfiguringPipeline.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.sln
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/Azure.Configuration.csproj
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationClient.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationClient_private.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationSetting.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationSettingParser.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationWatcher.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/Options.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/README.md
Labels: Azure.ApplicationModel.Configuration, Client

#5264 Adding support for user-assigned identities for App Services
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/EndtoEndPositiveTests.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/Microsoft.Azure.Services.AppAuthentication.IntegrationTests.csproj
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.TestCommon/Constants.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.TestCommon/Microsoft.Azure.Services.AppAuthentication.TestCommon.csproj
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.Unit.Tests/Microsoft.Azure.Services.AppAuthentication.Unit.Tests.csproj
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.Unit.Tests/Mocks/MockMsi.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.Unit.Tests/MsiAccessTokenProviderTests.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.Unit.Tests/TokenHelper.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProviderFactory.cs
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/Microsoft.Azure.Services.AppAuthentication.csproj
  src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/MsiAccessTokenProvider.cs
Labels: needs-review

#5248 Updated Kusto GA version
  src/SDKs/Kusto/AzSdk.RP.props
  src/SDKs/Kusto/Kusto.Tests/ScenarioTests/KustoOperationsTests.cs
  src/SDKs/Kusto/Kusto.Tests/ScenarioTests/KustoTestBase.cs
  src/SDKs/Kusto/Kusto.Tests/SessionRecords/Kusto.Tests.ScenarioTests.KustoOperationsTests/KustoClusterTests.json
  src/SDKs/Kusto/Kusto.Tests/SessionRecords/Kusto.Tests.ScenarioTests.KustoOperationsTests/KustoDataConnectionTests.json
  src/SDKs/Kusto/Kusto.Tests/SessionRecords/Kusto.Tests.ScenarioTests.KustoOperationsTests/KustoDatabasePrincipalsTests.json
  src/SDKs/Kusto/Kusto.Tests/SessionRecords/Kusto.Tests.ScenarioTests.KustoOperationsTests/KustoDatabaseTests.json
  src/SDKs/Kusto/Kusto.Tests/SessionRecords/Kusto.Tests.ScenarioTests.KustoOperationsTests/OperationsTest.json
  src/SDKs/Kusto/Management.Kusto/Generated/DatabasesOperations.cs
  src/SDKs/Kusto/Management.Kusto/Generated/IKustoManagementClient.cs
  src/SDKs/Kusto/Management.Kusto/Generated/KustoManagementClient.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/AzureCapacity.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/AzureResourceSku.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/AzureSku.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/AzureSkuName.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/CheckNameResult.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/Cluster.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/ClusterCheckNameRequest.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/ClusterUpdate.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DataFormat.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/Database.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DatabaseCheckNameRequest.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DatabasePrincipal.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DatabaseStatistics.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DatabaseUpdate.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/EventHubConnectionUpdate.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/State.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/TrustedExternalTenant.cs
  src/SDKs/Kusto/Management.Kusto/Generated/SdkInfo_KustoManagementClient.cs
  src/SDKs/Kusto/Management.Kusto/Microsoft.Azure.Management.Kusto.csproj
  src/SDKs/Kusto/Management.Kusto/Properties/AssemblyInfo.cs
  src/SDKs/Kusto/Management.Kusto/generate.ps1
  src/SDKs/Kusto/Management.Kusto/generated/DataConnectionsOperations.cs
  src/SDKs/Kusto/Management.Kusto/generated/DataConnectionsOperationsExtensions.cs
  src/SDKs/Kusto/Management.Kusto/generated/IDataConnectionsOperations.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/DataConnection.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/DataConnectionValidation.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/DataConnectionValidationListResult.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/DataConnectionValidationResult.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/EventGridDataConnection.cs
  src/SDKs/Kusto/Management.Kusto/generated/Models/EventHubDataConnection.cs
  src/SDKs/_metadata/Azure-Kusto_resource-manager.txt
  src/SDKs/_metadata/Kusto_resource-manager.txt
Labels: Changes Requested

#5280 [DataFactory] Updating the SDK with latest swagger changes and preparing for release
  src/SDKs/DataFactory/DataFactory.Tests/JsonSamples/LinkedServiceJsonSamples.cs
  src/SDKs/DataFactory/DataFactory.Tests/JsonSamples/PipelineJsonSamples.cs
  src/SDKs/DataFactory/Management.DataFactory/Generated/Models/AzureDatabricksLinkedService.cs
  src/SDKs/DataFactory/Management.DataFactory/Generated/Models/CustomActivity.cs
  src/SDKs/DataFactory/Management.DataFactory/Generated/SdkInfo_DataFactoryManagementClient.cs
  src/SDKs/DataFactory/Management.DataFactory/Microsoft.Azure.Management.DataFactory.csproj
  src/SDKs/DataFactory/Management.DataFactory/changelog.md
  src/SDKs/_metadata/datafactory_resource-manager.txt
Labels: Changes Requested

#5286 Public Preview of Mixed Reality Cloud Service
  src/SDKs/MixedReality/AzSdk.RP.props
  src/SDKs/MixedReality/Management.MixedReality/Generated/IMixedRealityClient.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/IOperations.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/ISpatialAnchorsAccountsOperations.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/MixedRealityClient.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/MixedRealityClientExtensions.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/AzureEntityResource.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/CheckNameAvailabilityRequest.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/CheckNameAvailabilityResponse.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/ErrorResponse.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/ErrorResponseException.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/NameAvailability.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/NameUnavailableReason.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/Operation.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/OperationDisplay.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/Page.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/ProxyResource.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/Resource.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/SpatialAnchorsAccount.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/SpatialAnchorsAccountKeyRegenerateRequest.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/SpatialAnchorsAccountKeys.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Models/TrackedResource.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/Operations.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/OperationsExtensions.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/SdkInfo_MixedRealityClient.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/SpatialAnchorsAccountsOperations.cs
  src/SDKs/MixedReality/Management.MixedReality/Generated/SpatialAnchorsAccountsOperationsExtensions.cs
  src/SDKs/MixedReality/Management.MixedReality/Microsoft.Azure.Management.MixedReality.csproj
  src/SDKs/MixedReality/Management.MixedReality/generate.ps1
  src/SDKs/MixedReality/MixedReality.Tests/Common/MixedRealityTests.cs
  src/SDKs/MixedReality/MixedReality.Tests/MixedReality.Tests.csproj
  src/SDKs/MixedReality/MixedReality.Tests/Properties/AssemblyInfo.cs
  src/SDKs/MixedReality/MixedReality.Tests/ScenarioTests/OperationsTests.cs
  src/SDKs/MixedReality/MixedReality.Tests/ScenarioTests/SpatialAnchorsAccountTests.cs
  src/SDKs/MixedReality/MixedReality.Tests/SessionRecords/MixedReality.Tests.OperationsTests/TestListMixedRealityOperations.json
  src/SDKs/MixedReality/MixedReality.Tests/SessionRecords/MixedReality.Tests.SpatialAnchorsAccountTests/TestSpatialAnchorsAccountOperations.json
  src/SDKs/MixedReality/MixedReality.sln
  src/SDKs/_metadata/mixedreality_resource-manager.txt
Labels: Changes Requested

#5287 Moved some types to Azure root namespace
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationClient.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/Attributes/HttpErrorAttribute.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/Attributes/KnownExceptionAttribute.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/Attributes/UsageErrorsAttribute.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/ETag.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/ETagFilter.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/FailedResponseException.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/Net/UriExtensions.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/Response.cs
  src/SDKs/Azure.Base/data-plane/Azure.Base/ResponseOfT.cs
Labels: Azure.ApplicationModel.Configuration, Client

#5291 Update repo reference for AzConfig samples
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/README.md
Labels: Azure.ApplicationModel.Configuration, Client

#5294 [AzConfig] Hide request id
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/ConfigurationLiveTests.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationClient.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/ConfigurationClient_private.cs
  src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration/Options.cs
Labels: Azure.ApplicationModel.Configuration, Client
