Repository Azure/azure-sdk-for-net, pull requests merged in 2019-05, with the labels that each got.

#5861 AutoPr-Monitor-meday89-REST Spec PrNumber 5677
  src/SDKs/Monitor/Management.Monitor/Generated/Models/DynamicMetricCriteria.cs
  src/SDKs/Monitor/Management.Monitor/Generated/Models/DynamicThresholdFailingPeriods.cs
  src/SDKs/Monitor/Management.Monitor/Generated/Models/LogToMetricAction.cs
  src/SDKs/Monitor/Management.Monitor/Generated/Models/MetricCriteria.cs
  src/SDKs/Monitor/Management.Monitor/Generated/Models/MultiMetricCriteria.cs
Labels: spec-not-merged

#6045 [Event Hubs Client] Test Revisions and Improvements
  sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/AzureStorageCheckpointLeaseManager.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ClientNegativeCases.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ClientTestBase.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ConnectionStringBuilderTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/DataBatchTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/DiagnosticsTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/MiscTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/PartitionPumpTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ReceiverRuntimeMetricsTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ReceiverTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/RuntimeInformationTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/SendTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/TimeoutTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/WebSocketTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Infrastructure/TaskExtensions.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Instrastructure.Tests/TaskExtensionTests.cs
  sdk/eventhub/Microsoft.Azure.EventHubs/tests/Processor/ProcessorNegativeCases.cs
Labels: Client, Event Hubs, Test Debt

#6083 [Engineering System] Increase Timeout for Live Tests
  .azure-pipelines/tests.yml
Labels: Client, EngSys, Event Hubs

#6129 [Engineering System] Increase Timeout for Live Tests
  .azure-pipelines/tests.yml
Labels: Client, EngSys, Event Hubs

#6160 Update AppConfig doc with preview2
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/README.md
Labels: AzConfig, Client

#6176 Pipeline templates
  eng/pipelines/templates/jobs/tests.yml
  sdk/appconfiguration/tests.yml
  sdk/core/tests.yml
  sdk/eventhub/tests.yml
  sdk/keyvault/tests.yml
  sdk/servicebus/tests.yml
Labels: EngSys

#6164 Updated Hybrid data manager version number to 1.0.0
  src/SDKs/HybridDataManager/Management.HybridData/Management.HybridData.csproj
Labels: Changes Requested

#5798 AutoPr-Kusto-liatbezalel-REST Spec PrNumber 5648
  src/SDKs/Kusto/Management.Kusto/Generated/DataConnectionsOperations.cs
  src/SDKs/Kusto/Management.Kusto/Generated/DataConnectionsOperationsExtensions.cs
  src/SDKs/Kusto/Management.Kusto/Generated/IDataConnectionsOperations.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/CheckNameResult.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/DataConnectionCheckNameRequest.cs
  src/SDKs/Kusto/Management.Kusto/Generated/Models/Reason.cs
  src/SDKs/Kusto/Management.Kusto/Generated/SdkInfo_KustoManagementClient.cs
Labels: spec-not-merged

#6199 Update tests for Cdn service
  src/SDKs/Cdn/Cdn.Tests/ScenarioTests/CustomDomainTests.cs
  src/SDKs/Cdn/Cdn.Tests/ScenarioTests/EndpointTests.cs
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.CustomDomainTests/CustomDomainCRUDTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointCheckUsageTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointCreateTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointDeleteTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointGetListTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointPurgeLoadTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointStartStopTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/EndpointUpdateTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.EndpointTests/ValidateCustomDomainTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.GetEdgeNodeTests/GetEdgeNodeTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.NameAvailabilityTests/EndpointCheckNameAvailabilityTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.OperationsTests/ListOperationsTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.OriginTests/OriginGetListTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.OriginTests/OriginUpdateTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/GenerateSsoUriTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/GetSupportedOptimizationTypes.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileCheckUsageTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileCreateTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileDeleteTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileGetListTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileListBySubcriptionTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ProfileTests/ProfileUpdateTest.json
  src/SDKs/Cdn/Cdn.Tests/SessionRecords/Cdn.Tests.ScenarioTests.ValidateTests/ValidateProbePathTest.json
  src/SDKs/Cdn/Management.Cdn/Microsoft.Azure.Management.Cdn.csproj
  src/SDKs/Cdn/Management.Cdn/Properties/AssemblyInfo.cs
Labels: Changes Requested

#6137 AutoPr-ApplicationInsights-debugthings-REST Spec PrNumber 5870
  src/SDKs/ApplicationInsights/Management/Management.ApplicationInsights/Generated/IWorkItemConfigurationsOperations.cs
  src/SDKs/ApplicationInsights/Management/Management.ApplicationInsights/Generated/Models/WorkItemCreateConfiguration.cs
  src/SDKs/ApplicationInsights/Management/Management.ApplicationInsights/Generated/WorkItemConfigurationsOperations.cs
  src/SDKs/ApplicationInsights/Management/Management.ApplicationInsights/Generated/WorkItemConfigurationsOperationsExtensions.cs
Labels: spec-not-merged

#6286 Normalize ProcessNext parameter order
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/AuthenticationPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/BearerTokenAuthenticationPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/BufferResponsePolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/LoggingPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/RetryPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/SynchronousHttpPipelinePolicy.cs
  sdk/storage/Azure.Storage.Common/src/SharedKeyPipelinePolicy.cs
  sdk/storage/Azure.Storage.Common/src/TokenPipelinePolicy.cs
  sdk/storage/Azure.Storage.Common/tests/Shared/FaultyHttpClientFactory.cs
Labels: breaking-change

#6303 Move logging policy to the base options type
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/ConfigurationClientOptions.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipeline.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelineOptions.cs
  sdk/keyvault/Azure.Security.Keyvault.Secrets/src/SecretClientOptions.cs
  sdk/storage/Azure.Storage.Common/src/StorageConnectionOptions.cs
Labels: breaking-change

#6305 [DevSpaces] 2019-04-01 API version update
  src/SDKs/DevSpaces/Management.DevSpaces/Microsoft.Azure.Management.DevSpaces.csproj
  src/SDKs/DevSpaces/Management.DevSpaces/Properties/AssemblyInfo.cs
Labels: Changes Requested

#6296 Make Storage Metadata case insensitive
  sdk/storage/Azure.Storage.Blobs/src/Generated/BlobRestClient.cs
  sdk/storage/Azure.Storage.Blobs/tests/TestHelper.cs
  sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts
  sdk/storage/Azure.Storage.Common/tests/Shared/TestHelper.Asserts.cs
  sdk/storage/Azure.Storage.Common/tests/Shared/TestHelper.cs
  sdk/storage/Azure.Storage.Files/src/Generated/FileRestClient.cs
  sdk/storage/Azure.Storage.Files/tests/TestHelper.cs
  sdk/storage/Azure.Storage.Queues/src/Generated/QueueRestClient.cs
  sdk/storage/Azure.Storage.Queues/tests/QueueClientTests.cs
  sdk/storage/Azure.Storage.Queues/tests/TestHelper.cs
Labels: Client, Storage, needs-review

#6316 Preserve whitespace when parsing XML
  sdk/storage/Azure.Storage.Blobs/src/Generated/BlobRestClient.cs
  sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs
  sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts
  sdk/storage/Azure.Storage.Files/src/Generated/FileRestClient.cs
  sdk/storage/Azure.Storage.Queues/src/Generated/QueueRestClient.cs
Labels: Client, Storage

#6261 AutoPr-StorageSync-afedyashov-REST Spec PrNumber 5941
  src/SDKs/StorageSync/AzSdk.RP.props
  src/SDKs/StorageSync/Management.StorageSync/Generated/CloudEndpointsOperations.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/CloudEndpointsOperationsExtensions.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/ICloudEndpointsOperations.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/IOperationStatusOperations.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/IStorageSyncManagementClient.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/ChangeDetectionMode.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/CloudEndpointCreateParameters.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/CloudEndpointsTriggerChangeDetectionHeaders.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/OperationStatus.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/OperationStatusGetHeaders.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/Models/TriggerChangeDetectionParameters.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/OperationStatusOperations.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/OperationStatusOperationsExtensions.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/SdkInfo_MicrosoftStorageSync.cs
  src/SDKs/StorageSync/Management.StorageSync/Generated/StorageSyncManagementClient.cs
Labels: spec-not-merged

#6325 New Websites SDK test recordings, assembly version update
  src/SDKs/WebSites/Management.Websites/Microsoft.Azure.Management.Websites.csproj
  src/SDKs/WebSites/Management.Websites/Properties/AssemblyInfo.cs
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.BackupRestoreScenarioTests/ListBackupsAndScheduledBackupRoundTrip.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.RecommendationScenarioTests/ListRecommendationsRoundTrip.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.ResourceHealthMetadataTests/GetResourceHealthMetadata.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.ResourceHealthMetadataTests/ListResourceHealthMetadata.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebHostingPlanScenarioTests/CreateAndDeleteWebHostingPlan.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebHostingPlanScenarioTests/CreateAndVerifyListOfWebHostingPlan.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebHostingPlanScenarioTests/CreateAndVerifyWebHostingPlan.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebHostingPlanScenarioTests/GetAndSetAdminSiteWebHostingPlan.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/CloneSite.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/CreateAndDeleteWebsite.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/CreateAndVerifyGetOnAWebsite.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/CreateAndVerifyListOfWebsites.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/GetAndSetNonSensitiveSiteConfigs.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/GetAndSetSensitiveSiteConfigs.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/GetAndSetSiteLimits.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteScenarioTests/GetAndSetSlotSettingsConfigs.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests/CreateAndDeleteWebSiteSlot.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests/CreateAndVerifyGetOnAWebsiteSlot.json
  src/SDKs/WebSites/WebSites.Tests/SessionRecords/WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests/CreateAndVerifyListOfSlots.json
Labels: Changes Requested

#6086 Event Grid data plane SDK: Update mappings in consumption SDK to include recently added EventGrid event types
  sdk/eventgrid/Microsoft.Azure.EventGrid/src/Customization/EventTypes.cs
  sdk/eventgrid/Microsoft.Azure.EventGrid/src/Customization/SystemEventTypeMappings.cs
  sdk/eventgrid/Microsoft.Azure.EventGrid/src/Microsoft.Azure.EventGrid.csproj
  sdk/eventgrid/Microsoft.Azure.EventGrid/tests/Tests/ConsumeEventTests.cs
Labels: needs-review

#6413 Cleanup HttpPipelineMessage and HttpClientOptions
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/AuthenticationPolicy.cs
  sdk/core/Azure.Core/src/Collections/OptionsStore.cs
  sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs
  sdk/core/Azure.Core/src/Pipeline/HttpMessageOptions.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipeline.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelineMessage.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelineOptions.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelineRequestContent.cs
  sdk/core/Azure.Core/src/Pipeline/HttpPipelineTransport.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/BearerTokenAuthenticationPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/LoggingPolicy.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/RetryPolicy.cs
  sdk/core/Azure.Core/tests/HttpClientTransportFunctionalTests.cs
  sdk/core/Azure.Core/tests/HttpClientTransportTests.cs
  sdk/core/Azure.Core/tests/PipelineTestBase.cs
  sdk/core/Azure.Core/tests/PolicyTestBase.cs
  sdk/core/Azure.Core/tests/TestFramework/Mocks.cs
  sdk/core/Azure.Core/tests/TestFramework/RecordTransport.cs
  sdk/core/Azure.Core/tests/TestFramework/SyncAsyncPolicyTestBase.cs
Labels: breaking-change

#6412 Rename Raw to GetRawResponse
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/samples/Sample4_Logging.cs
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/tests/ConfigurationLiveTests.cs
  sdk/appconfiguration/Azure.ApplicationModel.Configuration/tests/ConfigurationWatcher.cs
  sdk/core/Azure.Core/Azure.Core.All.sln
  sdk/core/Azure.Core/src/ResponseOfT.cs
  sdk/keyvault/Azure.Security.Keyvault.Secrets/src/SecretClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlockList.cs
  sdk/storage/Azure.Storage.Blobs/src/Lease.cs
  sdk/storage/Azure.Storage.Blobs/tests/AppendBlobClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/BlobClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/BlockBlobClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/PageBlobClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/ServiceClientTests.cs
  sdk/storage/Azure.Storage.Files/src/FileClient.cs
  sdk/storage/Azure.Storage.Files/tests/DirectoryClientTests.cs
  sdk/storage/Azure.Storage.Files/tests/FileClientTests.cs
  sdk/storage/Azure.Storage.Files/tests/ShareClientTests.cs
  sdk/storage/Azure.Storage.Queues/tests/MessageIdClientTests.cs
Labels: breaking-change

#6414 [Event Hubs Client] Skeleton API Track Two Preview 1
  eng/.docsettings.yml
  sdk/eventhub/Azure.Messaging.EventHubs/Azure.Messaging.EventHubs.sln
  sdk/eventhub/Azure.Messaging.EventHubs/Directory.Build.props
  sdk/eventhub/Azure.Messaging.EventHubs/README.md
  sdk/eventhub/Azure.Messaging.EventHubs/src/Azure.Messaging.EventHubs.csproj
  sdk/eventhub/Azure.Messaging.EventHubs/src/ConnectionType.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Core/Guard.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Core/MessagePropertyName.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventBatchingOptions.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubClient.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubClientOptions.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventPosition.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/EventSender.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/ExponentialRetry.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Metadata/EventHubProperties.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Metadata/PartitionProperties.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/PartitionReceiver.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Properties/AssemblyInfo.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/ReceiverOptions.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Resources.Designer.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/Resources.resx
  sdk/eventhub/Azure.Messaging.EventHubs/src/Retry.cs
  sdk/eventhub/Azure.Messaging.EventHubs/src/SenderOptions.cs
  sdk/eventhub/Azure.Messaging.EventHubs/tests/Azure.Messaging.EventHubs.Tests.csproj
  sdk/eventhub/Azure.Messaging.EventHubs/tests/xunit.runner.json
  sdk/servicebus/Microsoft.Azure.ServiceBus/tests/QueueSessionTests.cs
Labels: Client, Event Hubs

#6420 Add sync support to retriable stream
  sdk/core/Azure.Core/src/Buffers/Transcoder.cs
  sdk/core/Azure.Core/src/Diagnostics/HttpPipelineEventSource.cs
  sdk/core/Azure.Core/src/Pipeline/Policies/LoggingPolicy.cs
  sdk/core/Azure.Core/src/RetriableStream.cs
  sdk/core/Azure.Core/tests/EventSourceTests.cs
  sdk/core/Azure.Core/tests/RetriableStreamTests.cs
  sdk/core/Azure.Core/tests/TestFramework/AsyncValidatingStream.cs
  sdk/core/Azure.Core/tests/TestFramework/Mocks.cs
  sdk/core/Azure.Core/tests/TestFramework/SyncAsyncPolicyTestBase.cs
  sdk/core/Azure.Core/tests/TestFramework/SyncAsyncTestBase.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs
  sdk/storage/Azure.Storage.Files/src/FileClient.cs
Labels: breaking-change

#6425 Keys API changes after the API Review
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/Azure.Security.Keyvault.Keys.csproj
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/DeletedKey.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/EcKeyCreateOptions.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/JsonWebKey.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/Key.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyAttributes.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyBase.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyClient.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyClientOptions.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyCreateOptions.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyCurveName.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyImportOptions.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyOperations.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyType.cs
  sdk/keyvault/Azure.Security.KeyVault.Keys/src/RsaKeyCreateOptions.cs
  sdk/keyvault/Azure.Security.KeyVault.sln
  sdk/keyvault/Azure.Security.Keyvault.Keys/src/EcKeyCreateOptions.cs
  sdk/keyvault/Azure.Security.Keyvault.Keys/src/JsonWebKeyCurveName.cs
  sdk/keyvault/Azure.Security.Keyvault.Keys/src/JsonWebKeyType.cs
  sdk/keyvault/Azure.Security.Keyvault.Keys/src/KeyCreateOptions.cs
  sdk/keyvault/Azure.Security.Keyvault.Keys/src/RsaKeyCreateOptions.cs
Labels: Client, KeyVault

#6310 [Cogs OCR] Update vision SDK per latest update from REST sepc
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/ComputerVisionClient.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/ComputerVisionClientExtensions.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/IComputerVisionClient.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/Line.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/ReadOperationResult.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/TextOperationResult.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/TextOperationStatusCodes.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/Word.cs
  sdk/cognitiveservices/Vision.ComputerVision/src/Microsoft.Azure.CognitiveServices.Vision.ComputerVision.csproj
  sdk/cognitiveservices/Vision.ComputerVision/tests/Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Tests.csproj
  sdk/cognitiveservices/Vision.ComputerVision/tests/SessionRecords/ComputerVisionSDK.Tests.VisionBatchReadFileTests/BatchReadFileInStreamTest.json
  sdk/cognitiveservices/Vision.ComputerVision/tests/SessionRecords/ComputerVisionSDK.Tests.VisionBatchReadFileTests/BatchReadFileTest.json
  sdk/cognitiveservices/Vision.ComputerVision/tests/SessionRecords/ComputerVisionSDK.Tests.VisionBatchReadFileTests/BatchReadPdfFileInStreamTest.json
  sdk/cognitiveservices/Vision.ComputerVision/tests/TestImages/menu.pdf
  sdk/cognitiveservices/Vision.ComputerVision/tests/VisionBatchReadFileTests.cs
  src/SDKs/_metadata/cognitiveservices_data-plane_ComputerVision.txt
Labels: needs-review
