Repository Azure/azure-sdk-for-net, pull requests merged in 2025-03, with the labels that each got.

#48496 Increment version for ai releases
  sdk/ai/Azure.AI.Projects/CHANGELOG.md
  sdk/ai/Azure.AI.Projects/src/Azure.AI.Projects.csproj
Labels: AI Model Inference, AI Projects

#48465 [SRP] Update with latest Swagger
  sdk/storage/Azure.ResourceManager.Storage/src/Generated/FileShareData.Serialization.cs
  sdk/storage/Azure.ResourceManager.Storage/src/autorest.md
Labels: Mgmt

#48509 Increment version for quota releases
  sdk/quota/Azure.ResourceManager.Quota/CHANGELOG.md
  sdk/quota/Azure.ResourceManager.Quota/src/Azure.ResourceManager.Quota.csproj
Labels: Quota

#48511 Increment version for storage releases
  sdk/storage/Azure.ResourceManager.Storage/CHANGELOG.md
  sdk/storage/Azure.ResourceManager.Storage/src/Azure.ResourceManager.Storage.csproj
Labels: Mgmt

#48495 [Governance] Fix outdated references
  eng/Packages.Data.props
  sdk/cloudmachine/Azure.CloudMachine.OpenAI/src/Azure.CloudMachine.OpenAI.csproj
  sdk/cloudmachine/Azure.CloudMachine.Web/src/Azure.CloudMachine.Web.csproj
  sdk/cloudmachine/Azure.CloudMachine/src/Azure.CloudMachine.csproj
  sdk/extension-wcf/Microsoft.WCF.Azure.StorageQueues/src/Microsoft.WCF.Azure.StorageQueues.csproj
  sdk/extension-wcf/Microsoft.WCF.Azure.StorageQueues/tests/Microsoft.WCF.Azure.StorageQueues.Tests.csproj
  sdk/extension-wcf/samples/Microsoft.WCF.Azure.StorageQueues.Samples/Microsoft.WCF.Azure.StorageQueues.Samples.csproj
  sdk/keyvault/samples/sharelink/ShareLink.csproj
  sdk/purview/Azure.Analytics.Purview.Workflows/README.md
  sdk/purview/Azure.Analytics.Purview.Workflows/samples/Sample1_Workflows.md
  sdk/purview/Azure.Analytics.Purview.Workflows/samples/Sample2_SubmitUserRequests.md
  sdk/purview/Azure.Analytics.Purview.Workflows/samples/Sample3_WorkflowTasks.md
  sdk/purview/Azure.Analytics.Purview.Workflows/samples/Sample4_WorkflowRuns.md
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/Samples/Sample1_HelloWorld.cs
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/Samples/Sample2_SubmitUserRequests.cs
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/Samples/Sample3_WorkflowTasks.cs
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/Samples/Sample4_WorkflowRuns.cs
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/WorkflowsClientTestBase.cs
  sdk/purview/Azure.Analytics.Purview.Workflows/tests/WorkflowsClientTestEnvironment.cs
  sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSubForSocketIO/samples/SampleDev-JavaScript/package-lock.json
  sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSubForSocketIO/samples/SampleDev-JavaScript/package.json
Labels: Client, EngSys

#48506 Prepare release of SignalR extensions 2.0
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/CHANGELOG.md
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj
Labels: SignalR

#48519 Sync eng/common directory with azure-sdk-tools for PR 9955
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#48521 Sync eng/common directory with azure-sdk-tools for PR 9945
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#48512 Update AutoRest C# version to 3.0.0-beta.20250303.1
  eng/Packages.Data.props
  eng/emitter-package-lock.json
  eng/emitter-package.json
  sdk/communication/Azure.Communication.Messages/tspCodeModel.json
Labels: Communication

#48529 Delete Resourcemanager Service.Props, trigger core tests on changes to resourcemanager
  sdk/core/ci.yml
  sdk/resourcemanager/service.projects
Labels: Azure.Core

#48507 Add platform id to feedback template
  .github/ISSUE_TEMPLATE/06_learn_feedback.yml
Labels: customer-reported, Community Contribution

#48534 Increment version for signalr releases
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/CHANGELOG.md
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj
Labels: SignalR

#48538 Increment version for servicenetworking releases
  sdk/servicenetworking/Azure.ResourceManager.ServiceNetworking/CHANGELOG.md
  sdk/servicenetworking/Azure.ResourceManager.ServiceNetworking/src/Azure.ResourceManager.ServiceNetworking.csproj
Labels: Mgmt

#48546 Added AppConfig and Chat Completion Helper APIs
  eng/Packages.Data.props
  sdk/cloudmachine/Azure.Projects.OpenAI/api/Azure.Projects.OpenAI.net8.0.cs
  sdk/cloudmachine/Azure.Projects.OpenAI/api/Azure.Projects.OpenAI.netstandard2.0.cs
  sdk/cloudmachine/Azure.Projects.OpenAI/src/CHatProcessor.cs
  sdk/cloudmachine/Azure.Projects.Provisioning/api/Azure.Projects.Provisioning.net8.0.cs
  sdk/cloudmachine/Azure.Projects.Provisioning/api/Azure.Projects.Provisioning.netstandard2.0.cs
  sdk/cloudmachine/Azure.Projects.Provisioning/src/Azure.Projects.Provisioning.csproj
  sdk/cloudmachine/Azure.Projects.Provisioning/src/FeaturesExtensions/AppConfigurationFeature.cs
  sdk/cloudmachine/Azure.Projects.Provisioning/tests/BicepGenerationTests.cs
  sdk/cloudmachine/Azure.Projects.Provisioning/tests/Data/appConfig.bicep
  sdk/cloudmachine/Azure.Projects.Provisioning/tests/E2ETests.cs
  sdk/cloudmachine/Azure.Projects.sln
  sdk/cloudmachine/Azure.Projects/api/Azure.Projects.net8.0.cs
  sdk/cloudmachine/Azure.Projects/api/Azure.Projects.netstandard2.0.cs
  sdk/cloudmachine/Azure.Projects/samples/HelloRAG/Program.cs
  sdk/cloudmachine/Azure.Projects/samples/HelloWorld/Program.cs
  sdk/cloudmachine/Azure.Projects/samples/OFXRAG/.gitignore
  sdk/cloudmachine/Azure.Projects/samples/OFXRAG/OFXRAG.csproj
  sdk/cloudmachine/Azure.Projects/samples/OFXRAG/Program.cs
  sdk/cloudmachine/Azure.Projects/samples/RAGMachine/Program.cs
  sdk/cloudmachine/Azure.Projects/src/Azure.Projects.csproj
  sdk/cloudmachine/Azure.Projects/src/extensions/AppConfigurationExtensions.cs
Labels: Cloud Machine

#48550 [CODEOWNERS] Fix linter errors
  .github/CODEOWNERS
Labels: Client, EngSys

#48552 [Storage] [Docs] Added documentation on AggregateException
  sdk/storage/Azure.Storage.Blobs/src/AppendBlobClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobLeaseClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobServiceClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs
  sdk/storage/Azure.Storage.Blobs/src/PageBlobClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeDirectoryClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileSystemClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeLeaseClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakePathClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeServiceClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareDirectoryClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareLeaseClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareServiceClient.cs
  sdk/storage/Azure.Storage.Queues/src/QueueClient.cs
  sdk/storage/Azure.Storage.Queues/src/QueueServiceClient.cs
Labels: Storage

#48354 Log the ManagedIdentityId when ManagedIdentityCredential is selected
  sdk/identity/Azure.Identity/CHANGELOG.md
  sdk/identity/Azure.Identity/api/Azure.Identity.net8.0.cs
  sdk/identity/Azure.Identity/api/Azure.Identity.netstandard2.0.cs
  sdk/identity/Azure.Identity/src/AzureIdentityEventSource.cs
  sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs
  sdk/identity/Azure.Identity/src/ManagedIdentityId.cs
  sdk/identity/Azure.Identity/tests/ManagedIdentityCredentialTests.cs
Labels: Azure.Identity

#48527 [Extensions] Add AzurePipelinesCredential support
  sdk/extensions/Azure.Extensions.sln
  sdk/extensions/Microsoft.Extensions.Azure/CHANGELOG.md
  sdk/extensions/Microsoft.Extensions.Azure/src/Internal/ClientFactory.cs
  sdk/extensions/Microsoft.Extensions.Azure/tests/ClientFactoryTests.cs
  sdk/extensions/Microsoft.Extensions.Azure/tests/compatibility/ExpectedAotWarnings.txt
  sdk/extensions/ci.yml
Labels: Client, Extensions

#48556 fixed change logs for text authoring and conversation authoring
  sdk/cognitivelanguage/Azure.AI.Language.Conversations.Authoring/CHANGELOG.md
  sdk/cognitivelanguage/Azure.AI.Language.Text.Authoring/CHANGELOG.md
Labels: Cognitive - Language

#47692 Added get recording result api.
  sdk/communication/Azure.Communication.CallAutomation/api/Azure.Communication.CallAutomation.net8.0.cs
  sdk/communication/Azure.Communication.CallAutomation/api/Azure.Communication.CallAutomation.netstandard2.0.cs
  sdk/communication/Azure.Communication.CallAutomation/src/CallRecording.cs
  sdk/communication/Azure.Communication.CallAutomation/tests/CallRecordings/CallRecordingAutomatedLiveTests.cs
Labels: Communication

#48542 ContainerService Pre-Release
  sdk/containerservice/Azure.ResourceManager.ContainerService/CHANGELOG.md
  sdk/containerservice/Azure.ResourceManager.ContainerService/src/Azure.ResourceManager.ContainerService.csproj
Labels: Mgmt

#48568 Increment version for containerservice releases
  sdk/containerservice/Azure.ResourceManager.ContainerService/CHANGELOG.md
  sdk/containerservice/Azure.ResourceManager.ContainerService/src/Azure.ResourceManager.ContainerService.csproj
Labels: Mgmt

#48572 Sync eng/common directory with azure-sdk-tools for PR 9982
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#48200 Updating azure rooms SDK for collaborator role
  sdk/communication/Azure.Communication.Rooms/CHANGELOG.md
  sdk/communication/Azure.Communication.Rooms/README.md
  sdk/communication/Azure.Communication.Rooms/api/Azure.Communication.Rooms.net8.0.cs
  sdk/communication/Azure.Communication.Rooms/api/Azure.Communication.Rooms.netstandard2.0.cs
  sdk/communication/Azure.Communication.Rooms/assets.json
  sdk/communication/Azure.Communication.Rooms/src/AssemblyInfo.cs
  sdk/communication/Azure.Communication.Rooms/src/Azure.Communication.Rooms.csproj
  sdk/communication/Azure.Communication.Rooms/src/Generated/Models/ParticipantRole.cs
  sdk/communication/Azure.Communication.Rooms/src/Generated/Models/UpdateRoomRequest.cs
  sdk/communication/Azure.Communication.Rooms/src/Generated/ParticipantsRestClient.cs
  sdk/communication/Azure.Communication.Rooms/src/Generated/RoomsRestClient.cs
  sdk/communication/Azure.Communication.Rooms/src/RoomsClient.cs
  sdk/communication/Azure.Communication.Rooms/src/RoomsClientOptions.cs
  sdk/communication/Azure.Communication.Rooms/src/autorest.md
  sdk/communication/Azure.Communication.Rooms/tests/RoomsClient/RoomClientPstnDialOutLiveTest.cs
  sdk/communication/Azure.Communication.Rooms/tests/Samples/Sample1_RoomsClient.cs
  sdk/communication/Azure.Communication.Rooms/tests/Samples/Sample1_RoomsRequests.md
Labels: Communication - Rooms

#48582 Add net462 API listings
  sdk/core/Azure.Core.Experimental/api/Azure.Core.Experimental.net462.cs
  sdk/core/Azure.Core/api/Azure.Core.net462.cs
Labels: Azure.Core

#48551 Sync eng/common directory with azure-sdk-tools for PR 9918
  eng/common/scripts/job-matrix/pullrequest-faq.md
Labels: EngSys, Central-EngSys

#48580 [Storage] Redact SAS credentials from Error.SasCredentialRequiresUriWithoutSas message
  sdk/storage/Azure.Storage.Blobs/assets.json
  sdk/storage/Azure.Storage.Blobs/tests/BlobSasBuilderTests.cs
  sdk/storage/Azure.Storage.Common/CHANGELOG.md
  sdk/storage/Azure.Storage.Common/src/Shared/Errors.Clients.cs
  sdk/storage/Azure.Storage.Files.DataLake/assets.json
  sdk/storage/Azure.Storage.Files.DataLake/tests/DataLakeSasBuilderTests.cs
  sdk/storage/Azure.Storage.Files.Shares/assets.json
  sdk/storage/Azure.Storage.Files.Shares/tests/FileSasBuilderTests.cs
  sdk/storage/Azure.Storage.Queues/assets.json
  sdk/storage/Azure.Storage.Queues/tests/QueueSasBuilderTests.cs
Labels: Storage

#48553 [AzureMonitor] simplify preprocessors
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Azure.Monitor.OpenTelemetry.AspNetCore.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.AspNetCoreTestApp/Program.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Demo/Program.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Demo/ProgramNet461Compat.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/BaseLiveTest.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/DistroWebAppLiveTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/TelemetryValidationHelper.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/AzureSdkLoggingTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/DefaultAzureMonitorOptionsTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/E2ETests/AspNetCoreInstrumentationTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/E2ETests/SqlClientInstrumentationTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/E2ETests/TestHttpServer.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/LiveMetrics/DocumentTests/HttpClientDependecyTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/LiveMetrics/DocumentTests/RequestTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/OpenTelemetryBuilderExtensionsTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Azure.Monitor.OpenTelemetry.Exporter.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/IngestionResponseHelper.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/SourceGenerationContext.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/Statsbeat/AzureMonitorStatsbeat.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/TraceHelper.cs
Labels: Monitor - Exporter, Monitor - Distro

#48486 Sync eng/common directory with azure-sdk-tools for PR 9943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#48605 Prepare SCM release
  sdk/core/System.ClientModel/CHANGELOG.md
Labels: Azure.Core

#48439 [Search] 2025-03-01-preview: regenerated from the latest swagger
  sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.net8.0.cs
  sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.netstandard2.0.cs
  sdk/search/Azure.Search.Documents/assets.json
  sdk/search/Azure.Search.Documents/src/Generated/AliasesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/DataSourcesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/DocumentsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/IndexersRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/IndexesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/AIServicesAccountIdentity.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/AIServicesAccountIdentity.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/BinaryQuantizationCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/IndexStatisticsSummary.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/IndexStatisticsSummary.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ListIndexStatsSummary.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ListIndexStatsSummary.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ScalarQuantizationCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchDocumentsResult.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchDocumentsResult.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerCache.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerCache.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchResourceEncryptionKey.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SemanticConfiguration.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SemanticConfiguration.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/UnknownVectorSearchCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/VectorSearchCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs
  sdk/search/Azure.Search.Documents/src/Generated/SearchServiceRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/SkillsetsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/SynonymMapsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Indexes/Models/SearchResourceEncryptionKey.cs
  sdk/search/Azure.Search.Documents/src/Models/SearchModelFactory.cs
  sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs
  sdk/search/Azure.Search.Documents/src/SearchClientOptions.cs
  sdk/search/Azure.Search.Documents/src/Utilities/Constants.cs
  sdk/search/Azure.Search.Documents/src/autorest.md
  sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs
  sdk/search/Azure.Search.Documents/tests/DocumentOperations/VectorSearchTests.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample01_HelloWorld.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample07_VectorSearch_SemanticHybridSearch.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample08_SemanticSearch.cs
  sdk/search/Azure.Search.Documents/tests/SearchIndexClientTests.cs
  sdk/search/Azure.Search.Documents/tests/SearchIndexerClientTests.cs
Labels: Search, Client

#48606 Update CHANGELOG.md
  sdk/communication/Azure.Communication.CallAutomation/CHANGELOG.md
Labels: Communication

#48575 [smoke test] version correction for testing smoke test
  eng/scripts/smoketest/Get-Package-Version.ps1
Labels: Central-EngSys

#48587 Increment version for cognitivelanguage releases
  sdk/cognitivelanguage/Azure.AI.Language.Conversations.Authoring/CHANGELOG.md
  sdk/cognitivelanguage/Azure.AI.Language.Conversations.Authoring/src/Azure.AI.Language.Conversations.Authoring.csproj
  sdk/cognitivelanguage/Azure.AI.Language.Text.Authoring/CHANGELOG.md
  sdk/cognitivelanguage/Azure.AI.Language.Text.Authoring/src/Azure.AI.Language.Text.Authoring.csproj
Labels: Cognitive - Language

#48609 [Storage] Rerecorded tests after changes to OpenRead default byte value
  sdk/storage/Azure.Storage.DataMovement.Blobs.Files.Shares/assets.json
  sdk/storage/Azure.Storage.DataMovement.Blobs/assets.json
  sdk/storage/Azure.Storage.DataMovement.Files.Shares/assets.json
Labels: Storage

#48620 remove autorest.md in `Azure.Monitor.OpenTelemetry.AspNetCore`
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/autorest.md
Labels: Monitor - Distro

#48626 Remove username and password env vars from README
  sdk/identity/Azure.Identity/README.md
Labels: Azure.Identity

#48549 Light up CAE support for ManagedIdentityCredential
  eng/Packages.Data.props
  sdk/identity/Azure.Identity/CHANGELOG.md
  sdk/identity/Azure.Identity/src/MsalManagedIdentityClient.cs
  sdk/identity/Azure.Identity/tests/ManagedIdentityCredentialTests.cs
  sdk/identity/Azure.Identity/tests/Mock/MockMsalManagedIdentityClient.cs
Labels: Azure.Identity

#48574 [AzureMonitor] upgrade OTel to v1.11
  eng/Packages.Data.props
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/CHANGELOG.md
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Vendoring/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/SessionRecords/DistroWebAppLiveTests/VerifyDistro.json
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/SessionRecords/DistroWebAppLiveTests/VerifySendingToTwoResources_UsingDistroWithExporter.json
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Integration.Tests/SessionRecords/DistroWebAppLiveTests/VerifySendingToTwoResources_UsingExporter.json
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/E2ETests/HttpClientInstrumentationTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/LiveMetrics/DocumentTests/ActivityEventTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.LiveMetrics.Demo/Program.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/CHANGELOG.md
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/perf/Scenarios/ActivityKindClient.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/perf/Scenarios/ActivityKindServer.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/TraceHelper.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Demo/Traces/TraceDemo.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/E2ETelemetryItemValidation/TracesTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/RemoteDependencyDataNewTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/RemoteDependencyDataTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/RequestDataNewTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/RequestDataTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/TraceHelperTests.cs
Labels: Monitor - Exporter, Monitor - Distro

#48612 Increment version for core releases
  sdk/core/System.ClientModel/CHANGELOG.md
  sdk/core/System.ClientModel/src/System.ClientModel.csproj
Labels: Azure.Core

#48631 Prepare for release
  sdk/identity/Azure.Identity.Broker/CHANGELOG.md
  sdk/identity/Azure.Identity/CHANGELOG.md
Labels: Azure.Identity

#48628 [Storage] Implement IAsyncDisposable in StorageWriteStream
  sdk/storage/Azure.Storage.Common/CHANGELOG.md
  sdk/storage/Azure.Storage.Common/src/Shared/StorageWriteStream.cs
Labels: Storage

#48630 Update SCM to latest version and change ProjectReference to PackageReference
  sdk/ai/Azure.AI.Inference/src/Azure.AI.Inference.csproj
  sdk/ai/Azure.AI.Projects/src/Azure.AI.Projects.csproj
  sdk/cloudmachine/Azure.Projects/src/Azure.Projects.csproj
  sdk/openai/Azure.AI.OpenAI/src/Azure.AI.OpenAI.csproj
  sdk/search/Azure.Search.Documents/src/Azure.Search.Documents.csproj
Labels: Search, OpenAI, AI Model Inference, Cloud Machine, AI Projects

#48611 [Storage] [DataMovement] Add Datamovement to Storage CI
  sdk/storage/ci.yml
Labels: Storage

#48557 [Storage][DataMovement] Ensure single call downloads are queued to chunk channel
  sdk/storage/Azure.Storage.DataMovement/src/UriToStreamJobPart.cs
Labels: Storage

#48444 fix typos in RehydrationToken's doc
  sdk/core/Azure.Core/src/RehydrationToken.cs
Labels: Azure.Core

#48656 Update AutoRest C# version to 3.0.0-beta.20250309.1
  eng/Packages.Data.props
  eng/emitter-package-lock.json
  eng/emitter-package.json
  sdk/batch/Azure.Compute.Batch/tsp-location.yaml
  sdk/communication/Azure.Communication.Messages/tspCodeModel.json
Labels: Communication

#48573 [Microsoft.DataProtection] Dot net SDK release for AdlsBlobBackupDatasourceParameters Swagger 2025-02-01
  sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/autorest.md
Labels: Mgmt

#48625 Add new TeamsExtensionUserIdentifier and new computed properties for PhoneNumberIdentifier
  sdk/communication/Azure.Communication.Common/CHANGELOG.md
  sdk/communication/Azure.Communication.Common/api/Azure.Communication.Common.net8.0.cs
  sdk/communication/Azure.Communication.Common/api/Azure.Communication.Common.netstandard2.0.cs
  sdk/communication/Azure.Communication.Common/src/CommunicationIdentifier.cs
  sdk/communication/Azure.Communication.Common/src/MicrosoftTeamsUserIdentifier.cs
  sdk/communication/Azure.Communication.Common/src/PhoneNumberIdentifier.cs
  sdk/communication/Azure.Communication.Common/src/TeamsExtensionUserIdentifier.cs
  sdk/communication/Azure.Communication.Common/tests/CommunicationIdentifierTest.cs
  sdk/communication/Shared/src/CommunicationIdentifierSerializer.cs
  sdk/communication/Shared/src/CommunicationIdentifierSerializer_2025_03_15_preview.cs
Labels: Communication, Communication - Common

#48579 Fix BlobContainerClient reference to auth policy
  sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs
  sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs
  sdk/storage/Azure.Storage.Common/src/Shared/StorageClientOptions.cs
  sdk/storage/Azure.Storage.Common/tests/Shared/StorageAuthType.cs
Labels: Storage

#48669 Obsolete UsernamePasswordCredentialOptions
  sdk/identity/Azure.Identity/api/Azure.Identity.net8.0.cs
  sdk/identity/Azure.Identity/api/Azure.Identity.netstandard2.0.cs
  sdk/identity/Azure.Identity/src/Credentials/UsernamePasswordCredentialOptions.cs
Labels: Azure.Identity

#48670 Sync eng/common directory with azure-sdk-tools for PR 10013
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#48633 [AzureMonitor] include LiveMetrics in Exporter project
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Azure.Monitor.OpenTelemetry.AspNetCore.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/AzureMonitorAspNetCoreEventSource.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/AzureMonitorOptions.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/OpenTelemetryBuilderExtensions.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Tests/LiveMetrics/LiveMetricsPolingIntervalTests.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Azure.Monitor.OpenTelemetry.Exporter.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/SdkVersionUtils.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Properties/AssemblyInfo.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.AotCompatibilityTestApp/ExpectedAotWarnings.txt
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/AzureMonitorLiveMetricsEventSource.cs
  sdk/monitor/ci.yml
Labels: Monitor - Exporter, Monitor - Distro, Monitor - LiveMetrics

#48673 [AppConfig] build: v1.6.0 release prep
  sdk/appconfiguration/Azure.Data.AppConfiguration/CHANGELOG.md
  sdk/appconfiguration/Azure.Data.AppConfiguration/src/Azure.Data.AppConfiguration.csproj
Labels: App Configuration

#48636 [Storage] Fixed bug where connection string with account name not set in Storage Client
  sdk/storage/Azure.Storage.Blobs/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobServiceClient.cs
  sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs
  sdk/storage/Azure.Storage.Blobs/tests/ServiceClientTests.cs
  sdk/storage/Azure.Storage.Common/CHANGELOG.md
  sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs
  sdk/storage/Azure.Storage.Common/tests/Shared/TestExtensions.cs
  sdk/storage/Azure.Storage.Files.DataLake/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeDirectoryClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileSystemClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakePathClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeServiceClient.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/DirectoryClientTests.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/FileClientTests.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/FileSystemClientTests.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/PathClientTests.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/ServiceClientTests.cs
  sdk/storage/Azure.Storage.Files.Shares/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.Shares/src/ShareClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareDirectoryClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareServiceClient.cs
  sdk/storage/Azure.Storage.Files.Shares/tests/DirectoryClientTests.cs
  sdk/storage/Azure.Storage.Files.Shares/tests/FileClientTests.cs
  sdk/storage/Azure.Storage.Files.Shares/tests/ServiceClientTests.cs
  sdk/storage/Azure.Storage.Files.Shares/tests/ShareClientTests.cs
  sdk/storage/Azure.Storage.Queues/CHANGELOG.md
  sdk/storage/Azure.Storage.Queues/src/QueueClient.cs
  sdk/storage/Azure.Storage.Queues/src/QueueServiceClient.cs
  sdk/storage/Azure.Storage.Queues/tests/QueueClientTests.cs
  sdk/storage/Azure.Storage.Queues/tests/ServiceClientTests.cs
Labels: Storage

#48638 [emitter] Move over Azure branded tests to azure-sdk-for-net emitter
  eng/packages/http-client-csharp/emitter/test/Unit/property-type.test.ts
  eng/packages/http-client-csharp/emitter/test/Unit/scalar.test.ts
  eng/packages/http-client-csharp/emitter/test/Unit/test-util.ts
  eng/packages/http-client-csharp/emitter/test/Unit/usage.test.ts
Labels: Client, CodeGen

#48672 Fixing EventProcessor.Checkpoint span duration
  sdk/eventhub/Azure.Messaging.EventHubs.Processor/CHANGELOG.md
  sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs
Labels: Event Hubs

#48640 [AzureMonitor] refactor EventSource after LiveMetrics move
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/AzureMonitorAspNetCoreEventSource.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/ConnectionString/ConnectionStringParser.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/Platform/DefaultPlatform.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/SdkVersionUtils.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/AzureMonitorLiveMetricsEventSource.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Customizations/LiveMetricsRestAPIsForClientSDKsRestClient.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/DataCollection/DocumentHelper.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/LiveMetricsClientManager.MetricsCollection.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/LiveMetricsClientManager.RestClient.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/LiveMetricsClientManager.StateManagement.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/LiveMetricsClientManager.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.LiveMetrics/src/Internals/LiveMetricsRedirectPolicy.cs
Labels: Monitor - Exporter, Monitor - Distro, Monitor - LiveMetrics

#48682 [CODEOWNERS] Remove retired label
  .github/CODEOWNERS
Labels: Client, EngSys

#48686 Prepare release for Azure.ResourceManager.ResourceGraph
  sdk/resourcegraph/Azure.ResourceManager.ResourceGraph/CHANGELOG.md
Labels: Mgmt

#48643 Pre-release for apimanagement to Astro
  sdk/apimanagement/Azure.ResourceManager.ApiManagement/CHANGELOG.md
  sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation/CHANGELOG.md
  sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation/src/Azure.ResourceManager.AppComplianceAutomation.csproj
  sdk/applicationinsights/Azure.ResourceManager.ApplicationInsights/CHANGELOG.md
  sdk/applicationinsights/Azure.ResourceManager.ApplicationInsights/src/Azure.ResourceManager.ApplicationInsights.csproj
  sdk/appplatform/Azure.ResourceManager.AppPlatform/CHANGELOG.md
  sdk/appplatform/Azure.ResourceManager.AppPlatform/src/Azure.ResourceManager.AppPlatform.csproj
  sdk/arc-scvmm/Azure.ResourceManager.ScVmm/CHANGELOG.md
  sdk/astronomer/Azure.ResourceManager.Astro/CHANGELOG.md
Labels: Mgmt, Astronomer

#48645 pre-release from chaos to cnooectedvm
  sdk/chaos/Azure.ResourceManager.Chaos/CHANGELOG.md
  sdk/communication/Azure.ResourceManager.Communication/CHANGELOG.md
  sdk/communication/Azure.ResourceManager.Communication/src/Azure.ResourceManager.Communication.csproj
  sdk/confidentialledger/Azure.ResourceManager.ConfidentialLedger/CHANGELOG.md
  sdk/confluent/Azure.ResourceManager.Confluent/CHANGELOG.md
  sdk/confluent/Azure.ResourceManager.Confluent/src/Azure.ResourceManager.Confluent.csproj
  sdk/connectedvmwarevsphere/Azure.ResourceManager.ConnectedVMwarevSphere/CHANGELOG.md
  sdk/connectedvmwarevsphere/Azure.ResourceManager.ConnectedVMwarevSphere/src/Azure.ResourceManager.ConnectedVMwarevSphere.csproj
Labels: Mgmt, Communication - Resource Manager

#48644 pre-release for AzureLargeInstance to Cdn
  sdk/azurelargeinstance/Azure.ResourceManager.LargeInstance/CHANGELOG.md
  sdk/azurestackhci/Azure.ResourceManager.Hci/CHANGELOG.md
  sdk/azurestackhci/Azure.ResourceManager.Hci/src/Azure.ResourceManager.Hci.csproj
  sdk/billing/Azure.ResourceManager.Billing/CHANGELOG.md
  sdk/billing/Azure.ResourceManager.Billing/src/Azure.ResourceManager.Billing.csproj
  sdk/cdn/Azure.ResourceManager.Cdn/CHANGELOG.md
  sdk/cdn/Azure.ResourceManager.Cdn/src/Azure.ResourceManager.Cdn.csproj
Labels: Network - CDN, Mgmt, Large Instance

#48646 pre-release from Consumption to FrontDoor
  sdk/consumption/Azure.ResourceManager.Consumption/CHANGELOG.md
  sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/CHANGELOG.md
  sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Azure.ResourceManager.DesktopVirtualization.csproj
  sdk/deviceprovisioningservices/Azure.ResourceManager.DeviceProvisioningServices/CHANGELOG.md
  sdk/deviceprovisioningservices/Azure.ResourceManager.DeviceProvisioningServices/src/Azure.ResourceManager.DeviceProvisioningServices.csproj
  sdk/eventgrid/Azure.ResourceManager.EventGrid/CHANGELOG.md
  sdk/frontdoor/Azure.ResourceManager.FrontDoor/CHANGELOG.md
  sdk/frontdoor/Azure.ResourceManager.FrontDoor/src/Azure.ResourceManager.FrontDoor.csproj
Labels: Mgmt, Network - Front Door

#48695 Increment version for resourcegraph releases
  sdk/resourcegraph/Azure.ResourceManager.ResourceGraph/CHANGELOG.md
  sdk/resourcegraph/Azure.ResourceManager.ResourceGraph/src/Azure.ResourceManager.ResourceGraph.csproj
Labels: Mgmt

#48702 Increment version for arc-scvmm releases
  sdk/arc-scvmm/Azure.ResourceManager.ScVmm/CHANGELOG.md
  sdk/arc-scvmm/Azure.ResourceManager.ScVmm/src/Azure.ResourceManager.ScVmm.csproj
Labels: Mgmt

#48700 Increment version for apimanagement releases
  sdk/apimanagement/Azure.ResourceManager.ApiManagement/CHANGELOG.md
  sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Azure.ResourceManager.ApiManagement.csproj
Labels: Mgmt

#48706 Increment version for connectedvmwarevsphere releases
  sdk/connectedvmwarevsphere/Azure.ResourceManager.ConnectedVMwarevSphere/CHANGELOG.md
  sdk/connectedvmwarevsphere/Azure.ResourceManager.ConnectedVMwarevSphere/src/Azure.ResourceManager.ConnectedVMwarevSphere.csproj
Labels: Mgmt

#48709 Increment version for communication releases
  sdk/communication/Azure.ResourceManager.Communication/CHANGELOG.md
  sdk/communication/Azure.ResourceManager.Communication/src/Azure.ResourceManager.Communication.csproj
Labels: Communication - Resource Manager

#48701 Increment version for astronomer releases
  sdk/astronomer/Azure.ResourceManager.Astro/CHANGELOG.md
  sdk/astronomer/Azure.ResourceManager.Astro/src/Azure.ResourceManager.Astro.csproj
Labels: Astronomer

#48705 Increment version for confluent releases
  sdk/confluent/Azure.ResourceManager.Confluent/CHANGELOG.md
  sdk/confluent/Azure.ResourceManager.Confluent/src/Azure.ResourceManager.Confluent.csproj
Labels: Mgmt

#48708 Increment version for appcomplianceautomation releases
  sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation/CHANGELOG.md
  sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation/src/Azure.ResourceManager.AppComplianceAutomation.csproj
Labels: Mgmt

#48707 Increment version for applicationinsights releases
  sdk/applicationinsights/Azure.ResourceManager.ApplicationInsights/CHANGELOG.md
  sdk/applicationinsights/Azure.ResourceManager.ApplicationInsights/src/Azure.ResourceManager.ApplicationInsights.csproj
Labels: Mgmt

#48704 Increment version for chaos releases
  sdk/chaos/Azure.ResourceManager.Chaos/CHANGELOG.md
  sdk/chaos/Azure.ResourceManager.Chaos/src/Azure.ResourceManager.Chaos.csproj
Labels: Mgmt

#48703 Increment version for confidentialledger releases
  sdk/confidentialledger/Azure.ResourceManager.ConfidentialLedger/CHANGELOG.md
  sdk/confidentialledger/Azure.ResourceManager.ConfidentialLedger/src/Azure.ResourceManager.ConfidentialLedger.csproj
Labels: Mgmt

#48680 Storage STG 97 GA release prep
  sdk/storage/Azure.Storage.Blobs.Batch/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs.Batch/src/Azure.Storage.Blobs.Batch.csproj
  sdk/storage/Azure.Storage.Blobs.ChangeFeed/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs/src/Azure.Storage.Blobs.csproj
  sdk/storage/Azure.Storage.Common/CHANGELOG.md
  sdk/storage/Azure.Storage.Common/src/Azure.Storage.Common.csproj
  sdk/storage/Azure.Storage.Files.DataLake/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.DataLake/src/Azure.Storage.Files.DataLake.csproj
  sdk/storage/Azure.Storage.Files.Shares/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.Shares/src/Azure.Storage.Files.Shares.csproj
  sdk/storage/Azure.Storage.Queues/CHANGELOG.md
  sdk/storage/Azure.Storage.Queues/src/Azure.Storage.Queues.csproj
Labels: Storage

#48711 Increment version for frontdoor releases
  sdk/frontdoor/Azure.ResourceManager.FrontDoor/CHANGELOG.md
  sdk/frontdoor/Azure.ResourceManager.FrontDoor/src/Azure.ResourceManager.FrontDoor.csproj
Labels: Network - Front Door

#48712 Increment version for deviceprovisioningservices releases
  sdk/deviceprovisioningservices/Azure.ResourceManager.DeviceProvisioningServices/CHANGELOG.md
  sdk/deviceprovisioningservices/Azure.ResourceManager.DeviceProvisioningServices/src/Azure.ResourceManager.DeviceProvisioningServices.csproj
Labels: Mgmt

#48713 Increment version for eventgrid releases
  sdk/eventgrid/Azure.ResourceManager.EventGrid/CHANGELOG.md
  sdk/eventgrid/Azure.ResourceManager.EventGrid/src/Azure.ResourceManager.EventGrid.csproj
Labels: Mgmt

#48714 Increment version for appplatform releases
  sdk/appplatform/Azure.ResourceManager.AppPlatform/CHANGELOG.md
  sdk/appplatform/Azure.ResourceManager.AppPlatform/src/Azure.ResourceManager.AppPlatform.csproj
Labels: Mgmt

#48715 Increment version for cdn releases
  sdk/cdn/Azure.ResourceManager.Cdn/CHANGELOG.md
  sdk/cdn/Azure.ResourceManager.Cdn/src/Azure.ResourceManager.Cdn.csproj
Labels: Network - CDN

#48717 Increment version for azurestackhci releases
  sdk/azurestackhci/Azure.ResourceManager.Hci/CHANGELOG.md
  sdk/azurestackhci/Azure.ResourceManager.Hci/src/Azure.ResourceManager.Hci.csproj
Labels: Mgmt

#48718 Increment version for billing releases
  sdk/billing/Azure.ResourceManager.Billing/CHANGELOG.md
  sdk/billing/Azure.ResourceManager.Billing/src/Azure.ResourceManager.Billing.csproj
Labels: Mgmt

#48719 Increment version for consumption releases
  sdk/consumption/Azure.ResourceManager.Consumption/CHANGELOG.md
  sdk/consumption/Azure.ResourceManager.Consumption/src/Azure.ResourceManager.Consumption.csproj
Labels: Mgmt

#48720 Increment version for desktopvirtualization releases
  sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/CHANGELOG.md
  sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Azure.ResourceManager.DesktopVirtualization.csproj
Labels: Mgmt

#48723 [AppConfig] chore: rename ConfigurationAudience
  sdk/appconfiguration/Azure.Data.AppConfiguration/api/Azure.Data.AppConfiguration.net8.0.cs
  sdk/appconfiguration/Azure.Data.AppConfiguration/api/Azure.Data.AppConfiguration.netstandard2.0.cs
  sdk/appconfiguration/Azure.Data.AppConfiguration/src/AppConfigurationAudience.cs
  sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClientOptions.cs
  sdk/appconfiguration/Azure.Data.AppConfiguration/tests/AppConfigurationTestEnvironment.cs
  sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationClientOptionsTests.cs
Labels: App Configuration

#48722 [Search] Moving 2025-03-01-preview changes to main
  sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.net8.0.cs
  sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.netstandard2.0.cs
  sdk/search/Azure.Search.Documents/assets.json
  sdk/search/Azure.Search.Documents/src/Generated/AliasesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/DataSourcesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/DocumentsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/IndexersRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/IndexesRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/AIServicesAccountIdentity.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/AIServicesAccountIdentity.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/BinaryQuantizationCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/IndexStatisticsSummary.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/IndexStatisticsSummary.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ListIndexStatsSummary.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ListIndexStatsSummary.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/ScalarQuantizationCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchDocumentsResult.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchDocumentsResult.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerCache.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerCache.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SearchResourceEncryptionKey.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SemanticConfiguration.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/SemanticConfiguration.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/UnknownVectorSearchCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/Models/VectorSearchCompression.Serialization.cs
  sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs
  sdk/search/Azure.Search.Documents/src/Generated/SearchServiceRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/SkillsetsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Generated/SynonymMapsRestClient.cs
  sdk/search/Azure.Search.Documents/src/Indexes/Models/ListIndexStatsSummary.cs
  sdk/search/Azure.Search.Documents/src/Indexes/Models/SearchResourceEncryptionKey.cs
  sdk/search/Azure.Search.Documents/src/Indexes/SearchIndexClient.cs
  sdk/search/Azure.Search.Documents/src/Models/SearchModelFactory.cs
  sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs
  sdk/search/Azure.Search.Documents/src/SearchClientOptions.cs
  sdk/search/Azure.Search.Documents/src/Utilities/Constants.cs
  sdk/search/Azure.Search.Documents/src/autorest.md
  sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs
  sdk/search/Azure.Search.Documents/tests/DocumentOperations/VectorSearchTests.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample01_HelloWorld.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample07_VectorSearch_SemanticHybridSearch.cs
  sdk/search/Azure.Search.Documents/tests/Samples/Sample08_SemanticSearch.cs
  sdk/search/Azure.Search.Documents/tests/SearchIndexClientTests.cs
  sdk/search/Azure.Search.Documents/tests/SearchIndexerClientTests.cs
Labels: Search, Client

#48737 Sync eng/common directory with azure-sdk-tools for PR 10030
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#48739 Increment version for storage releases
  sdk/storage/Azure.Storage.Blobs.Batch/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs.Batch/src/Azure.Storage.Blobs.Batch.csproj
  sdk/storage/Azure.Storage.Files.DataLake/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.DataLake/src/Azure.Storage.Files.DataLake.csproj
Labels: Storage

#48732 Increment version for storage releases
  sdk/storage/Azure.Storage.Blobs.ChangeFeed/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs.ChangeFeed/src/Azure.Storage.Blobs.ChangeFeed.csproj
  sdk/storage/Azure.Storage.Blobs/CHANGELOG.md
  sdk/storage/Azure.Storage.Blobs/src/Azure.Storage.Blobs.csproj
  sdk/storage/Azure.Storage.Common/CHANGELOG.md
  sdk/storage/Azure.Storage.Common/src/Azure.Storage.Common.csproj
  sdk/storage/Azure.Storage.Files.Shares/CHANGELOG.md
  sdk/storage/Azure.Storage.Files.Shares/src/Azure.Storage.Files.Shares.csproj
  sdk/storage/Azure.Storage.Queues/CHANGELOG.md
  sdk/storage/Azure.Storage.Queues/src/Azure.Storage.Queues.csproj
Labels: Storage

#48744 Fix SignalR trigger completion message serialization for dotnet-isola…
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/CHANGELOG.md
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj
  sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/TriggerBindings/Utils/JTokenWrapper.cs
Labels: SignalR

#48734 Increment version for identity releases
  sdk/identity/Azure.Identity.Broker/CHANGELOG.md
  sdk/identity/Azure.Identity.Broker/src/Azure.Identity.Broker.csproj
  sdk/identity/Azure.Identity/CHANGELOG.md
  sdk/identity/Azure.Identity/src/Azure.Identity.csproj
Labels: Azure.Identity

#48730 [Governance] Update WCF Extensions
  eng/Packages.Data.props
  sdk/extension-wcf/Microsoft.CoreWCF.Azure.StorageQueues/src/Microsoft.CoreWCF.Azure.StorageQueues.csproj
  sdk/extension-wcf/Microsoft.WCF.Azure.StorageQueues/src/Microsoft.WCF.Azure.StorageQueues.csproj
  sdk/extension-wcf/Microsoft.WCF.Azure.StorageQueues/src/Microsoft/WCF/Azure/AzureClientCredentials.cs
Labels: Client, EngSys

#48752 Remove old link from MICredential XML docs
  sdk/identity/Azure.Identity/src/Credentials/ManagedIdentityCredential.cs
Labels: Azure.Identity

#48754 STG 99 service version
  sdk/storage/Azure.Storage.Blobs.ChangeFeed/tests/ChangeFeedTestBase.cs
  sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.net6.0.cs
  sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.net8.0.cs
  sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs
  sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.1.cs
  sdk/storage/Azure.Storage.Blobs/src/BlobClientOptions.cs
  sdk/storage/Azure.Storage.Blobs/tests/BlobsClientTestFixtureAttribute.cs
  sdk/storage/Azure.Storage.Common/api/Azure.Storage.Common.net6.0.cs
  sdk/storage/Azure.Storage.Common/api/Azure.Storage.Common.net8.0.cs
  sdk/storage/Azure.Storage.Common/api/Azure.Storage.Common.netstandard2.0.cs
  sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs
  sdk/storage/Azure.Storage.Common/src/Shared/StorageVersionExtensions.cs
  sdk/storage/Azure.Storage.Common/tests/CommonTestBase.cs
  sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.net6.0.cs
  sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.net8.0.cs
  sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs
  sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeClientOptions.cs
  sdk/storage/Azure.Storage.Files.DataLake/tests/DataLakeClientTestFixtureAttribute.cs
  sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.net6.0.cs
  sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.net8.0.cs
  sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs
  sdk/storage/Azure.Storage.Files.Shares/src/ShareClientOptions.cs
  sdk/storage/Azure.Storage.Files.Shares/tests/ShareClientTestFixtureAttribute.cs
  sdk/storage/Azure.Storage.Queues/api/Azure.Storage.Queues.net6.0.cs
  sdk/storage/Azure.Storage.Queues/api/Azure.Storage.Queues.net8.0.cs
  sdk/storage/Azure.Storage.Queues/api/Azure.Storage.Queues.netstandard2.0.cs
  sdk/storage/Azure.Storage.Queues/api/Azure.Storage.Queues.netstandard2.1.cs
  sdk/storage/Azure.Storage.Queues/src/QueueClientOptions.cs
  sdk/storage/Azure.Storage.Queues/tests/QueueClientTestFixtureAttribute.cs
Labels: Storage

#48758 Sync eng/common directory with azure-sdk-tools for PR 10028
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#48767 [AI Projects] Improve error message when no connection is found
  sdk/ai/Azure.AI.Projects/src/Custom/Connection/ConnectionsClient.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Extensions/Sample_AIInference.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Extensions/Sample_AzureOpenAI.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Extensions/Sample_Search.cs
Labels: AI Model Inference, AI Projects

#48766 Fix Bing sample to fail in case of run error
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agent_Bing_Grounding.cs
Labels: AI Model Inference, AI Projects

#48698 Azure.Resource.Manager.Authorization Pre-Release
  sdk/authorization/Azure.ResourceManager.Authorization/CHANGELOG.md
  sdk/authorization/Azure.ResourceManager.Authorization/src/Azure.ResourceManager.Authorization.csproj
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/DenyAssignmentCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/ProviderOperationsMetadataCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleAssignmentScheduleInstanceCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleAssignmentScheduleInstanceResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleAssignmentScheduleRequestCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleAssignmentScheduleRequestResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleAssignmentScheduleResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleDefinitionCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleDefinitionResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleEligibilityScheduleInstanceCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleEligibilityScheduleInstanceResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleEligibilityScheduleRequestCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleEligibilityScheduleRequestResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleEligibilityScheduleResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleManagementPolicyAssignmentCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleManagementPolicyAssignmentResourceTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleManagementPolicyCollectionTests.cs
  sdk/authorization/Azure.ResourceManager.Authorization/tests/Scenario/RoleManagementPolicyResourceTests.cs
Labels: Mgmt

#48649 pre-release from Iot to migrationDiscoverySap
  sdk/iot/Azure.ResourceManager.IotFirmwareDefense/CHANGELOG.md
  sdk/iot/Azure.ResourceManager.IotFirmwareDefense/src/Azure.ResourceManager.IotFirmwareDefense.csproj
  sdk/keyvault/Azure.ResourceManager.KeyVault/CHANGELOG.md
  sdk/keyvault/Azure.ResourceManager.KeyVault/src/Azure.ResourceManager.KeyVault.csproj
  sdk/machinelearningservices/Azure.ResourceManager.MachineLearning/CHANGELOG.md
  sdk/machinelearningservices/Azure.ResourceManager.MachineLearning/src/Azure.ResourceManager.MachineLearning.csproj
  sdk/maintenance/Azure.ResourceManager.Maintenance/CHANGELOG.md
  sdk/migrationdiscoverysap/Azure.ResourceManager.MigrationDiscoverySap/CHANGELOG.md
Labels: Mgmt

#48697 pre-release from MySql to Oracle
  sdk/mysql/Azure.ResourceManager.MySql/CHANGELOG.md
  sdk/mysql/Azure.ResourceManager.MySql/src/Azure.ResourceManager.MySql.csproj
  sdk/newrelicobservability/Azure.ResourceManager.NewRelicObservability/CHANGELOG.md
  sdk/newrelicobservability/Azure.ResourceManager.NewRelicObservability/src/Azure.ResourceManager.NewRelicObservability.csproj
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/CHANGELOG.md
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/src/Azure.ResourceManager.NotificationHubs.csproj
  sdk/oracle/Azure.ResourceManager.OracleDatabase/CHANGELOG.md
  sdk/oracle/Azure.ResourceManager.OracleDatabase/src/Azure.ResourceManager.OracleDatabase.csproj
Labels: Mgmt, New Relic

#48650 pre-release form Purview to redisenterprise
  sdk/purview/Azure.ResourceManager.Purview/CHANGELOG.md
  sdk/quantum/Azure.ResourceManager.Quantum/CHANGELOG.md
  sdk/qumulo/Azure.ResourceManager.Qumulo/CHANGELOG.md
  sdk/qumulo/Azure.ResourceManager.Qumulo/src/Azure.ResourceManager.Qumulo.csproj
  sdk/recoveryservices-siterecovery/Azure.ResourceManager.RecoveryServicesSiteRecovery/CHANGELOG.md
  sdk/recoveryservices-siterecovery/Azure.ResourceManager.RecoveryServicesSiteRecovery/src/Azure.ResourceManager.RecoveryServicesSiteRecovery.csproj
  sdk/redisenterprise/Azure.ResourceManager.RedisEnterprise/CHANGELOG.md
Labels: Mgmt

#48774 Increment version for hdinsight releases
  sdk/hdinsight/Azure.ResourceManager.HDInsight/CHANGELOG.md
  sdk/hdinsight/Azure.ResourceManager.HDInsight/src/Azure.ResourceManager.HDInsight.csproj
Labels: Mgmt

#48775 Increment version for hdinsightcontainers releases
  sdk/hdinsightcontainers/Azure.ResourceManager.HDInsight.Containers/CHANGELOG.md
  sdk/hdinsightcontainers/Azure.ResourceManager.HDInsight.Containers/src/Azure.ResourceManager.HDInsight.Containers.csproj
Labels: Mgmt

#48776 Increment version for redisenterprise releases
  sdk/redisenterprise/Azure.ResourceManager.RedisEnterprise/CHANGELOG.md
  sdk/redisenterprise/Azure.ResourceManager.RedisEnterprise/src/Azure.ResourceManager.RedisEnterprise.csproj
Labels: Mgmt

#48777 Increment version for guestconfiguration releases
  sdk/guestconfiguration/Azure.ResourceManager.GuestConfiguration/CHANGELOG.md
  sdk/guestconfiguration/Azure.ResourceManager.GuestConfiguration/src/Azure.ResourceManager.GuestConfiguration.csproj
Labels: Mgmt

#48778 Increment version for maintenance releases
  sdk/maintenance/Azure.ResourceManager.Maintenance/CHANGELOG.md
  sdk/maintenance/Azure.ResourceManager.Maintenance/src/Azure.ResourceManager.Maintenance.csproj
Labels: Mgmt

#48779 Increment version for healthcareapis releases
  sdk/healthcareapis/Azure.ResourceManager.HealthcareApis/CHANGELOG.md
  sdk/healthcareapis/Azure.ResourceManager.HealthcareApis/src/Azure.ResourceManager.HealthcareApis.csproj
Labels: Mgmt

#48780 Increment version for hybridaks releases
  sdk/hybridaks/Azure.ResourceManager.HybridContainerService/CHANGELOG.md
  sdk/hybridaks/Azure.ResourceManager.HybridContainerService/src/Azure.ResourceManager.HybridContainerService.csproj
Labels: Mgmt

#48781 Increment version for migrationdiscoverysap releases
  sdk/migrationdiscoverysap/Azure.ResourceManager.MigrationDiscoverySap/CHANGELOG.md
  sdk/migrationdiscoverysap/Azure.ResourceManager.MigrationDiscoverySap/src/Azure.ResourceManager.MigrationDiscoverySap.csproj
Labels: Mgmt

#48782 Increment version for newrelicobservability releases
  sdk/newrelicobservability/Azure.ResourceManager.NewRelicObservability/CHANGELOG.md
  sdk/newrelicobservability/Azure.ResourceManager.NewRelicObservability/src/Azure.ResourceManager.NewRelicObservability.csproj
Labels: New Relic

#48787 Increment version for keyvault releases
  sdk/keyvault/Azure.ResourceManager.KeyVault/CHANGELOG.md
  sdk/keyvault/Azure.ResourceManager.KeyVault/src/Azure.ResourceManager.KeyVault.csproj
Labels: Mgmt

#48785 Increment version for mysql releases
  sdk/mysql/Azure.ResourceManager.MySql/CHANGELOG.md
  sdk/mysql/Azure.ResourceManager.MySql/src/Azure.ResourceManager.MySql.csproj
Labels: Mgmt

#48784 Increment version for qumulo releases
  sdk/qumulo/Azure.ResourceManager.Qumulo/CHANGELOG.md
  sdk/qumulo/Azure.ResourceManager.Qumulo/src/Azure.ResourceManager.Qumulo.csproj
Labels: Mgmt

#48797 Increment version for iot releases
  sdk/iot/Azure.ResourceManager.IotFirmwareDefense/CHANGELOG.md
  sdk/iot/Azure.ResourceManager.IotFirmwareDefense/src/Azure.ResourceManager.IotFirmwareDefense.csproj
Labels: Mgmt

#48796 Increment version for machinelearningservices releases
  sdk/machinelearningservices/Azure.ResourceManager.MachineLearning/CHANGELOG.md
  sdk/machinelearningservices/Azure.ResourceManager.MachineLearning/src/Azure.ResourceManager.MachineLearning.csproj
Labels: Mgmt

#48791 Notificationhubs autorest.md required link update
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/src/autorest.md
Labels: Mgmt

#48800 Increment version for purview releases
  sdk/purview/Azure.ResourceManager.Purview/CHANGELOG.md
  sdk/purview/Azure.ResourceManager.Purview/src/Azure.ResourceManager.Purview.csproj
Labels: Mgmt

#48759 [Azure.AI.Projects] URL Citations
  sdk/ai/Azure.AI.Projects/CHANGELOG.md
  sdk/ai/Azure.AI.Projects/README.md
  sdk/ai/Azure.AI.Projects/api/Azure.AI.Projects.net8.0.cs
  sdk/ai/Azure.AI.Projects/api/Azure.AI.Projects.netstandard2.0.cs
  sdk/ai/Azure.AI.Projects/src/Custom/Agent/AgentsClient.Streaming.cs
  sdk/ai/Azure.AI.Projects/src/Generated/AIProjectsModelFactory.cs
  sdk/ai/Azure.AI.Projects/src/Generated/AgentsClient.cs
  sdk/ai/Azure.AI.Projects/src/Generated/CreateRunRequest.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/CreateRunRequest.cs
  sdk/ai/Azure.AI.Projects/src/Generated/CreateThreadAndRunRequest.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/CreateThreadAndRunRequest.cs
  sdk/ai/Azure.AI.Projects/src/Generated/InternalMessageTextDetails.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextAnnotation.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextAnnotation.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextContentObject.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextUrlCitationAnnotation.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextUrlCitationAnnotation.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextUrlCitationDetails.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageDeltaTextUrlCitationDetails.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextAnnotation.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextAnnotation.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextUrlCitationAnnotation.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextUrlCitationAnnotation.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextUrlCitationDetails.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/MessageTextUrlCitationDetails.cs
  sdk/ai/Azure.AI.Projects/src/Generated/RunStep.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/RunStep.cs
  sdk/ai/Azure.AI.Projects/src/Generated/ThreadMessage.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/ThreadMessage.cs
  sdk/ai/Azure.AI.Projects/src/Generated/ThreadRun.Serialization.cs
  sdk/ai/Azure.AI.Projects/src/Generated/ThreadRun.cs
  sdk/ai/Azure.AI.Projects/tests/AgentClientTests.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agent_Additional_messages.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agent_Basics.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agent_Bing_Grounding.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agent_Streaming.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Sample_Agents_Azure_AI_Search.cs
  sdk/ai/Azure.AI.Projects/tests/Samples/Agent/Samples_Agent_FileSearch.cs
  sdk/ai/Azure.AI.Projects/tsp-location.yaml
Labels: AI Model Inference, AI Projects

#48801 Increment version for notificationhubs releases
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/CHANGELOG.md
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/src/Azure.ResourceManager.NotificationHubs.csproj
Labels: Mgmt

#48770 updating the change log for the events change
  sdk/communication/Azure.Communication.CallAutomation/CHANGELOG.md
Labels: Communication

#48402 [AzureMonitorExporter] Add UseAzureMonitorExporter API with live metrics support
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.LiveMetrics.Demo/Azure.Monitor.OpenTelemetry.LiveMetrics.Demo.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.LiveMetrics.Demo/Program.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/api/Azure.Monitor.OpenTelemetry.Exporter.net8.0.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/api/Azure.Monitor.OpenTelemetry.Exporter.netstandard2.0.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Azure.Monitor.OpenTelemetry.Exporter.csproj
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorExporterOptions.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/DefaultAzureMonitorExporterOptions.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/ExporterRegistrationHostedService.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/Diagnostics/AzureMonitorExporterEventSource.cs
  sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/OpenTelemetryBuilderExtensions.cs
Labels: Monitor - Exporter

#48789 Sync eng/common directory with azure-sdk-tools for PR 10039
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#48813 Sync eng/common directory with azure-sdk-tools for PR 10041
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#48819 Increment version for notificationhubs releases
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/CHANGELOG.md
  sdk/notificationhubs/Azure.ResourceManager.NotificationHubs/src/Azure.ResourceManager.NotificationHubs.csproj
Labels: Mgmt

#48651 pre-release from Resources to Servicefabric
  sdk/resources/Azure.ResourceManager.Resources/CHANGELOG.md
  sdk/resources/Azure.ResourceManager.Resources/src/Azure.ResourceManager.Resources.csproj
  sdk/securitycenter/Azure.ResourceManager.SecurityCenter/CHANGELOG.md
  sdk/securityinsights/Azure.ResourceManager.SecurityInsights/CHANGELOG.md
  sdk/selfhelp/Azure.ResourceManager.SelfHelp/CHANGELOG.md
  sdk/servicefabric/Azure.ResourceManager.ServiceFabric/CHANGELOG.md
Labels: ARM, Mgmt, Self Help

#48804 Increment version for authorization releases
  sdk/authorization/Azure.ResourceManager.Authorization/CHANGELOG.md
  sdk/authorization/Azure.ResourceManager.Authorization/assets.json
  sdk/authorization/Azure.ResourceManager.Authorization/src/Azure.ResourceManager.Authorization.csproj
  sdk/iot/Azure.ResourceManager.IotFirmwareDefense/assets.json
Labels: Mgmt

#48652 pre-release from Sphere to StorageMover
  sdk/sphere/Azure.ResourceManager.Sphere/CHANGELOG.md
  sdk/sphere/Azure.ResourceManager.Sphere/src/Azure.ResourceManager.Sphere.csproj
  sdk/sqlmanagement/Azure.ResourceManager.Sql/CHANGELOG.md
  sdk/storageactions/Azure.ResourceManager.StorageActions/CHANGELOG.md
  sdk/storagecache/Azure.ResourceManager.StorageCache/CHANGELOG.md
  sdk/storagecache/Azure.ResourceManager.StorageCache/src/Azure.ResourceManager.StorageCache.csproj
  sdk/storagemover/Azure.ResourceManager.StorageMover/CHANGELOG.md
  sdk/storagemover/Azure.ResourceManager.StorageMover/src/Azure.ResourceManager.StorageMover.csproj
Labels: Mgmt

#48653 pre-release from Advisor to TrustedSigning
  sdk/advisor/Azure.ResourceManager.Advisor/CHANGELOG.md
  sdk/agrifood/Azure.ResourceManager.AgFoodPlatform/CHANGELOG.md
  sdk/support/Azure.ResourceManager.Support/CHANGELOG.md
  sdk/support/Azure.ResourceManager.Support/src/Azure.ResourceManager.Support.csproj
  sdk/trafficmanager/Azure.ResourceManager.TrafficManager/CHANGELOG.md
  sdk/trafficmanager/Azure.ResourceManager.TrafficManager/src/Azure.ResourceManager.TrafficManager.csproj
  sdk/trustedsigning/Azure.ResourceManager.TrustedSigning/CHANGELOG.md
Labels: Mgmt

#48654 pre-release from AlertsManagement to AutoManage
  sdk/alertsmanagement/Azure.ResourceManager.AlertsManagement/CHANGELOG.md
  sdk/alertsmanagement/Azure.ResourceManager.AlertsManagement/src/Azure.ResourceManager.AlertsManagement.csproj
  sdk/analysisservices/Azure.ResourceManager.Analysis/CHANGELOG.md
  sdk/analysisservices/Azure.ResourceManager.Analysis/src/Azure.ResourceManager.Analysis.csproj
  sdk/apicenter/Azure.ResourceManager.ApiCenter/CHANGELOG.md
  sdk/attestation/Azure.ResourceManager.Attestation/CHANGELOG.md
  sdk/automanage/Azure.ResourceManager.Automanage/CHANGELOG.md
  sdk/automanage/Azure.ResourceManager.Automanage/src/Azure.ResourceManager.Automanage.csproj
Labels: Mgmt

#48655 pre-release from Automation to ChangeAnalysis
  sdk/automation/Azure.ResourceManager.Automation/CHANGELOG.md
  sdk/automation/Azure.ResourceManager.Automation/src/Azure.ResourceManager.Automation.csproj
  sdk/billingbenefits/Azure.ResourceManager.BillingBenefits/CHANGELOG.md
  sdk/blueprint/Azure.ResourceManager.Blueprint/CHANGELOG.md
  sdk/botservice/Azure.ResourceManager.BotService/CHANGELOG.md
  sdk/botservice/Azure.ResourceManager.BotService/src/Azure.ResourceManager.BotService.csproj
  sdk/changeanalysis/Azure.ResourceManager.ChangeAnalysis/CHANGELOG.md
  sdk/changeanalysis/Azure.ResourceManager.ChangeAnalysis/src/Azure.ResourceManager.ChangeAnalysis.csproj
Labels: Mgmt

#48657 pre-release from CosmosDBSql to DataboxEdge
  sdk/cosmosdbforpostgresql/Azure.ResourceManager.CosmosDBForPostgreSql/CHANGELOG.md
  sdk/costmanagement/Azure.ResourceManager.CostManagement/CHANGELOG.md
  sdk/costmanagement/Azure.ResourceManager.CostManagement/src/Azure.ResourceManager.CostManagement.csproj
  sdk/customer-insights/Azure.ResourceManager.CustomerInsights/CHANGELOG.md
  sdk/databox/Azure.ResourceManager.DataBox/CHANGELOG.md
  sdk/databox/Azure.ResourceManager.DataBox/src/Azure.ResourceManager.DataBox.csproj
  sdk/databoxedge/Azure.ResourceManager.DataBoxEdge/CHANGELOG.md
  sdk/databoxedge/Azure.ResourceManager.DataBoxEdge/src/Azure.ResourceManager.DataBoxEdge.csproj
Labels: Mgmt

#48658 pre-release from DataDog to Defenderasm
  sdk/datadog/Azure.ResourceManager.Datadog/CHANGELOG.md
  sdk/datalake-analytics/Azure.ResourceManager.DataLakeAnalytics/CHANGELOG.md
  sdk/datalake-analytics/Azure.ResourceManager.DataLakeAnalytics/src/Azure.ResourceManager.DataLakeAnalytics.csproj
  sdk/datalake-store/Azure.ResourceManager.DataLakeStore/CHANGELOG.md
  sdk/datalake-store/Azure.ResourceManager.DataLakeStore/src/Azure.ResourceManager.DataLakeStore.csproj
  sdk/datamigration/Azure.ResourceManager.DataMigration/CHANGELOG.md
  sdk/datashare/Azure.ResourceManager.DataShare/CHANGELOG.md
  sdk/datashare/Azure.ResourceManager.DataShare/src/Azure.ResourceManager.DataShare.csproj
  sdk/defendereasm/Azure.ResourceManager.DefenderEasm/CHANGELOG.md
Labels: Mgmt

#48835 Increment version for automanage releases
  sdk/automanage/Azure.ResourceManager.Automanage/CHANGELOG.md
  sdk/automanage/Azure.ResourceManager.Automanage/src/Azure.ResourceManager.Automanage.csproj
Labels: Mgmt

#48838 Increment version for trustedsigning releases
  sdk/trustedsigning/Azure.ResourceManager.TrustedSigning/CHANGELOG.md
  sdk/trustedsigning/Azure.ResourceManager.TrustedSigning/src/Azure.ResourceManager.TrustedSigning.csproj
Labels: Mgmt

#48837 Increment version for analysisservices releases
  sdk/analysisservices/Azure.ResourceManager.Analysis/CHANGELOG.md
  sdk/analysisservices/Azure.ResourceManager.Analysis/src/Azure.ResourceManager.Analysis.csproj
Labels: Mgmt

#48836 Increment version for sphere releases
  sdk/sphere/Azure.ResourceManager.Sphere/CHANGELOG.md
  sdk/sphere/Azure.ResourceManager.Sphere/src/Azure.ResourceManager.Sphere.csproj
Labels: Mgmt

#48833 Increment version for advisor releases
  sdk/advisor/Azure.ResourceManager.Advisor/CHANGELOG.md
  sdk/advisor/Azure.ResourceManager.Advisor/src/Azure.ResourceManager.Advisor.csproj
Labels: Mgmt

#48832 Increment version for trafficmanager releases
  sdk/trafficmanager/Azure.ResourceManager.TrafficManager/CHANGELOG.md
  sdk/trafficmanager/Azure.ResourceManager.TrafficManager/src/Azure.ResourceManager.TrafficManager.csproj
Labels: Mgmt

#48831 Increment version for support releases
  sdk/support/Azure.ResourceManager.Support/CHANGELOG.md
  sdk/support/Azure.ResourceManager.Support/src/Azure.ResourceManager.Support.csproj
Labels: Mgmt

#48828 Increment version for agrifood releases
  sdk/agrifood/Azure.ResourceManager.AgFoodPlatform/CHANGELOG.md
  sdk/agrifood/Azure.ResourceManager.AgFoodPlatform/src/Azure.ResourceManager.AgFoodPlatform.csproj
Labels: Mgmt

#48826 Increment version for resources releases
  sdk/resources/Azure.ResourceManager.Resources/CHANGELOG.md
  sdk/resources/Azure.ResourceManager.Resources/src/Azure.ResourceManager.Resources.csproj
Labels: ARM

#48823 Increment version for storageactions releases
  sdk/storageactions/Azure.ResourceManager.StorageActions/CHANGELOG.md
  sdk/storageactions/Azure.ResourceManager.StorageActions/src/Azure.ResourceManager.StorageActions.csproj
Labels: Mgmt

#48821 Increment version for selfhelp releases
  sdk/selfhelp/Azure.ResourceManager.SelfHelp/CHANGELOG.md
  sdk/selfhelp/Azure.ResourceManager.SelfHelp/src/Azure.ResourceManager.SelfHelp.csproj
Labels: Self Help

#48820 Increment version for securitycenter releases
  sdk/securitycenter/Azure.ResourceManager.SecurityCenter/CHANGELOG.md
  sdk/securitycenter/Azure.ResourceManager.SecurityCenter/src/Azure.ResourceManager.SecurityCenter.csproj
Labels: Mgmt

#48830 Increment version for attestation releases
  sdk/attestation/Azure.ResourceManager.Attestation/CHANGELOG.md
  sdk/attestation/Azure.ResourceManager.Attestation/src/Azure.ResourceManager.Attestation.csproj
Labels: Mgmt

#48829 Increment version for storagecache releases
  sdk/storagecache/Azure.ResourceManager.StorageCache/CHANGELOG.md
  sdk/storagecache/Azure.ResourceManager.StorageCache/src/Azure.ResourceManager.StorageCache.csproj
Labels: Mgmt

#48827 Increment version for apicenter releases
  sdk/apicenter/Azure.ResourceManager.ApiCenter/CHANGELOG.md
  sdk/apicenter/Azure.ResourceManager.ApiCenter/src/Azure.ResourceManager.ApiCenter.csproj
Labels: Mgmt

#48822 Increment version for servicefabric releases
  sdk/servicefabric/Azure.ResourceManager.ServiceFabric/CHANGELOG.md
  sdk/servicefabric/Azure.ResourceManager.ServiceFabric/src/Azure.ResourceManager.ServiceFabric.csproj
Labels: Mgmt

#48825 Increment version for storagemover releases
  sdk/storagemover/Azure.ResourceManager.StorageMover/CHANGELOG.md
  sdk/storagemover/Azure.ResourceManager.StorageMover/src/Azure.ResourceManager.StorageMover.csproj
Labels: Mgmt
